[package]
name = "cli_docs_macro"
version = "0.2.0"
edition = "2024"
authors = ["Cesar Diaz"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
