[package]
name = "cobblepot_orm"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
cobblepot_core = { version = "0.1.0", path = "../cobblepot_core" }
diesel = { version = "2.2.1", features = ["sqlite", "chrono", "returning_clauses_for_sqlite_3_35"] }
rusty-money = "0.4.1"
