#[derive(PartialEq, Eq)]
pub enum VagueAccountType {
    Asset,
    Liability,
    Equity,
    Income,
    Expense,
}

impl From<&AccountType> for VagueAccountType {
    fn from(value: &AccountType) -> Self {
        match value {
            AccountType::AssetCash => VagueAccountType::Asset,
            AccountType::AssetSavings => VagueAccountType::Asset,
            AccountType::AssetChecking => VagueAccountType::Asset,
            AccountType::AssetInvestments => VagueAccountType::Asset,
            AccountType::AssetRetirementAccounts => VagueAccountType::Asset,
            AccountType::AssetAccountsReceivable => VagueAccountType::Asset,
            AccountType::AssetInventory => VagueAccountType::Asset,
            AccountType::AssetEquipment => VagueAccountType::Asset,
            AccountType::AssetRealEstate => VagueAccountType::Asset,
            AccountType::AssetVehicles => VagueAccountType::Asset,
            AccountType::AssetPrepaidExpenses => VagueAccountType::Asset,
            AccountType::AssetIntangibleAssets => VagueAccountType::Asset,
            AccountType::AssetOther => VagueAccountType::Asset,

            AccountType::LiabilityCreditCardDebt => VagueAccountType::Liability,
            AccountType::LiabilityPersonalLoans => VagueAccountType::Liability,
            AccountType::LiabilityBusinessLoans => VagueAccountType::Liability,
            AccountType::LiabilityAccountsPayable => VagueAccountType::Liability,
            AccountType::LiabilityMortgages => VagueAccountType::Liability,
            AccountType::LiabilityCarLoans => VagueAccountType::Liability,
            AccountType::LiabilityStudentLoans => VagueAccountType::Liability,
            AccountType::LiabilityTaxesPayable => VagueAccountType::Liability,
            AccountType::LiabilityWagesPayable => VagueAccountType::Liability,
            AccountType::LiabilityUtilitiesPayable => VagueAccountType::Liability,
            AccountType::LiabilityRentPayable => VagueAccountType::Liability,
            AccountType::LiabilityDeferredRevenue => VagueAccountType::Liability,
            AccountType::LiabilityAccruedExpenses => VagueAccountType::Liability,
            AccountType::LiabilityOther => VagueAccountType::Liability,

            AccountType::EquityOwnersEquity => VagueAccountType::Equity,
            AccountType::EquityRetainedEarnings => VagueAccountType::Equity,
            AccountType::EquityCapitalContributions => VagueAccountType::Equity,
            AccountType::EquityCommonStock => VagueAccountType::Equity,
            AccountType::EquityPreferredStock => VagueAccountType::Equity,
            AccountType::EquityAdditionalPaidInCapital => VagueAccountType::Equity,
            AccountType::EquityTreasuryStock => VagueAccountType::Equity,
            AccountType::EquityDividends => VagueAccountType::Equity,
            AccountType::EquityAccumulatedOtherComprehensiveIncome => VagueAccountType::Equity,
            AccountType::EquityOther => VagueAccountType::Equity,

            AccountType::IncomeSalary => VagueAccountType::Income,
            AccountType::IncomeBusinessRevenue => VagueAccountType::Income,
            AccountType::IncomeFreelanceIncome => VagueAccountType::Income,
            AccountType::IncomeInvestmentIncome => VagueAccountType::Income,
            AccountType::IncomeRentalIncome => VagueAccountType::Income,
            AccountType::IncomeInterestIncome => VagueAccountType::Income,
            AccountType::IncomeDividendIncome => VagueAccountType::Income,
            AccountType::IncomeCapitalGains => VagueAccountType::Income,
            AccountType::IncomeRoyalties => VagueAccountType::Income,
            AccountType::IncomeGrants => VagueAccountType::Income,
            AccountType::IncomeOther => VagueAccountType::Income,

            AccountType::ExpenseRent => VagueAccountType::Expense,
            AccountType::ExpenseUtilities => VagueAccountType::Expense,
            AccountType::ExpenseSalaries => VagueAccountType::Expense,
            AccountType::ExpenseWages => VagueAccountType::Expense,
            AccountType::ExpenseSupplies => VagueAccountType::Expense,
            AccountType::ExpenseInsurance => VagueAccountType::Expense,
            AccountType::ExpenseMarketing => VagueAccountType::Expense,
            AccountType::ExpenseTravel => VagueAccountType::Expense,
            AccountType::ExpenseMealsAndEntertainment => VagueAccountType::Expense,
            AccountType::ExpenseOfficeExpenses => VagueAccountType::Expense,
            AccountType::ExpenseLegalFees => VagueAccountType::Expense,
            AccountType::ExpenseAccountingFees => VagueAccountType::Expense,
            AccountType::ExpenseDepreciation => VagueAccountType::Expense,
            AccountType::ExpenseTaxes => VagueAccountType::Expense,
            AccountType::ExpenseInterestExpense => VagueAccountType::Expense,
            AccountType::ExpenseCostOfGoodsSold => VagueAccountType::Expense,
            AccountType::ExpenseMaintenanceAndRepairs => VagueAccountType::Expense,
            AccountType::ExpenseSubscriptions => VagueAccountType::Expense,
            AccountType::ExpenseOther => VagueAccountType::Expense,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AccountType {
    AssetCash,
    AssetSavings,
    AssetChecking,
    AssetInvestments,
    AssetRetirementAccounts,
    AssetAccountsReceivable,
    AssetInventory,
    AssetEquipment,
    AssetRealEstate,
    AssetVehicles,
    AssetPrepaidExpenses,
    AssetIntangibleAssets,
    AssetOther,

    LiabilityCreditCardDebt,
    LiabilityPersonalLoans,
    LiabilityBusinessLoans,
    LiabilityAccountsPayable,
    LiabilityMortgages,
    LiabilityCarLoans,
    LiabilityStudentLoans,
    LiabilityTaxesPayable,
    LiabilityWagesPayable,
    LiabilityUtilitiesPayable,
    LiabilityRentPayable,
    LiabilityDeferredRevenue,
    LiabilityAccruedExpenses,
    LiabilityOther,

    EquityOwnersEquity,
    EquityRetainedEarnings,
    EquityCapitalContributions,
    EquityCommonStock,
    EquityPreferredStock,
    EquityAdditionalPaidInCapital,
    EquityTreasuryStock,
    EquityDividends,
    EquityAccumulatedOtherComprehensiveIncome,
    EquityOther,

    IncomeSalary,
    IncomeBusinessRevenue,
    IncomeFreelanceIncome,
    IncomeInvestmentIncome,
    IncomeRentalIncome,
    IncomeInterestIncome,
    IncomeDividendIncome,
    IncomeCapitalGains,
    IncomeRoyalties,
    IncomeGrants,
    IncomeOther,

    ExpenseRent,
    ExpenseUtilities,
    ExpenseSalaries,
    ExpenseWages,
    ExpenseSupplies,
    ExpenseInsurance,
    ExpenseMarketing,
    ExpenseTravel,
    ExpenseMealsAndEntertainment,
    ExpenseOfficeExpenses,
    ExpenseLegalFees,
    ExpenseAccountingFees,
    ExpenseDepreciation,
    ExpenseTaxes,
    ExpenseInterestExpense,
    ExpenseCostOfGoodsSold,
    ExpenseMaintenanceAndRepairs,
    ExpenseSubscriptions,
    ExpenseOther,
}

#[derive(Debug, Clone, Copy)]
pub struct AccountCode {
    id: u16,
    pub account_type: AccountType,
}
