[package]
name = "cobblepot_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.cobblepot_core]
path = "../cobblepot_core"
version = "0.1.0"

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
colored = "2.0.0"
strum = "0.24"
strum_macros = "0.24"
