[package]
name = "cobblepot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.cobblepot_journal]
path = "../cobblepot_journal"
version = "0.1.0"
